#!/bin/bash

# Quick test commands for Guardz URL Fetcher Service
# Copy and paste these commands to test the API

SERVER_URL="http://34.135.82.223:8080/api"

echo "🚀 Quick Test Commands for Guardz URL Fetcher Service"
echo "====================================================="
echo ""
echo "1. Test with JSON and XML URLs:"
echo "curl -X POST -H \"Content-Type: application/json\" \\"
echo "  -d '{\"urls\": [\"https://httpbin.org/json\", \"https://httpbin.org/xml\"]}' \\"
echo "  $SERVER_URL/urls/fetch"
echo ""
echo "2. Test with multiple URLs:"
echo "curl -X POST -H \"Content-Type: application/json\" \\"
echo "  -d '{\"urls\": [\"https://httpbin.org/json\", \"https://httpbin.org/xml\", \"https://httpbin.org/html\"]}' \\"
echo "  $SERVER_URL/urls/fetch"
echo ""
echo "3. Test with real-world APIs:"
echo "curl -X POST -H \"Content-Type: application/json\" \\"
echo "  -d '{\"urls\": [\"https://api.github.com/users/octocat\", \"https://jsonplaceholder.typicode.com/posts/1\"]}' \\"
echo "  $SERVER_URL/urls/fetch"
echo ""
echo "4. Test error handling:"
echo "curl -X POST -H \"Content-Type: application/json\" \\"
echo "  -d '{\"urls\": [\"https://invalid-url.com\", \"https://httpbin.org/status/404\"]}' \\"
echo "  $SERVER_URL/urls/fetch"
echo ""
echo "5. Get all results:"
echo "curl $SERVER_URL/urls"
echo ""
echo "6. Get service status:"
echo "curl $SERVER_URL/urls/status"
echo ""
echo "====================================================="
echo "💡 Tip: Add | jq at the end for pretty JSON formatting"
echo "Example: curl $SERVER_URL/urls | jq"
